
package com.cpsmart.wexclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CardManagementWS", targetNamespace = "http://com.tch.cards.service", wsdlLocation = "https://ws.efsllc.com/axis2/services/CardManagementWS?wsdl")
public class CardManagementWS
    extends Service
{

    private final static URL CARDMANAGEMENTWS_WSDL_LOCATION;
    private final static WebServiceException CARDMANAGEMENTWS_EXCEPTION;
    private final static QName CARDMANAGEMENTWS_QNAME = new QName("http://com.tch.cards.service", "CardManagementWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws.efsllc.com/axis2/services/CardManagementWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDMANAGEMENTWS_WSDL_LOCATION = url;
        CARDMANAGEMENTWS_EXCEPTION = e;
    }

    public CardManagementWS() {
        super(__getWsdlLocation(), CARDMANAGEMENTWS_QNAME);
    }

    public CardManagementWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDMANAGEMENTWS_QNAME, features);
    }

    public CardManagementWS(URL wsdlLocation) {
        super(wsdlLocation, CARDMANAGEMENTWS_QNAME);
    }

    public CardManagementWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDMANAGEMENTWS_QNAME, features);
    }

    public CardManagementWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardManagementWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardManagementEP
     */
    @WebEndpoint(name = "CardManagementEPPort")
    public CardManagementEP getCardManagementEPPort() {
        return super.getPort(new QName("http://com.tch.cards.service", "CardManagementEPPort"), CardManagementEP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardManagementEP
     */
    @WebEndpoint(name = "CardManagementEPPort")
    public CardManagementEP getCardManagementEPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.tch.cards.service", "CardManagementEPPort"), CardManagementEP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDMANAGEMENTWS_EXCEPTION!= null) {
            throw CARDMANAGEMENTWS_EXCEPTION;
        }
        return CARDMANAGEMENTWS_WSDL_LOCATION;
    }

}
