
package com.cpsmart.wexclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CardManagementEP", targetNamespace = "http://com.tch.cards.service")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CardManagementEP {


    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSCarrierInfo
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCarrierInfo getCarrierInfo(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public int createNewPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param description
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "policy", partName = "policy")
    public int createNewSitePolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "description", mode = WebParam.Mode.INOUT, partName = "description")
        Holder<String> description);

    /**
     * 
     * @param clientId
     * @param policyNum
     * @param policies
     * @param addremoveall
     */
    @WebMethod
    public void setSitePolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNum", partName = "policyNum")
        int policyNum,
        @WebParam(name = "addremoveall", partName = "addremoveall")
        String addremoveall,
        @WebParam(name = "policies", mode = WebParam.Mode.INOUT, partName = "policies")
        Holder<WSSitePolicyList> policies);

    /**
     * 
     * @param clientId
     * @param cardNumber
     */
    @WebMethod
    public void deleteOverride(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSCard
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCard getCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSCardv2
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCardv2 getCardv2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param clientId
     * @param driverId
     * @return
     *     returns com.cpsmart.wexclient.WSCard
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCard getCardByDriverId(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSSmartPayDriver
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayDriver getSmartPayDriver(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param clientId
     * @param createdSince
     * @return
     *     returns com.cpsmart.wexclient.WSCardDescriptionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCardDescriptionArray getCardDescriptions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "createdSince", partName = "createdSince")
        XMLGregorianCalendar createdSince);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSCashRecordArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCashRecordArray getCashHistory(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @param cardNumber
     * @param cardStatus
     * @return
     *     returns com.cpsmart.wexclient.WSCashRecordArrayV2
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCashRecordArrayV2 getCashHistoryV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate,
        @WebParam(name = "cardStatus", partName = "cardStatus")
        String cardStatus);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSCashRecordArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCashRecordArray getPayrollCashHistory(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @param cardNumber
     * @param cardStatus
     * @return
     *     returns com.cpsmart.wexclient.WSCashRecordArrayV2
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCashRecordArrayV2 getPayrollCashHistoryV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate,
        @WebParam(name = "cardStatus", partName = "cardStatus")
        String cardStatus);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSContractArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSContractArray getContracts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param cardNumbers
     * @return
     *     returns com.cpsmart.wexclient.DoubleArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public DoubleArray getCurrentCashAmounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumbers", partName = "cardNumbers")
        StringArray cardNumbers);

    /**
     * 
     * @param clientId
     * @param cardNumbers
     * @return
     *     returns com.cpsmart.wexclient.DoubleArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public DoubleArray getCurrentPayrollCashAmounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumbers", partName = "cardNumbers")
        StringArray cardNumbers);

    /**
     * 
     * @param clientId
     * @param alphaCode
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeHistRec
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeHistRec getMoneyCode(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "alphaCode", partName = "alphaCode")
        String alphaCode);

    /**
     * 
     * @param clientId
     * @param alphaCode
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeHistRecV2
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeHistRecV2 getMoneyCodeV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "alphaCode", partName = "alphaCode")
        String alphaCode);

    /**
     * 
     * @param codeId
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeById
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeById getMoneyCodeById(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "codeId", partName = "codeId")
        int codeId);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @param contractId
     * @param masterContractId
     * @param issued
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeUseArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeUseArray getMoneyCodeUse(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId,
        @WebParam(name = "masterContractId", partName = "masterContractId")
        int masterContractId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate,
        @WebParam(name = "issued", partName = "issued")
        boolean issued);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @param contractId
     * @param masterContractId
     * @param issued
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeUseArrayV2
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeUseArrayV2 getMoneyCodeUseV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId,
        @WebParam(name = "masterContractId", partName = "masterContractId")
        int masterContractId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate,
        @WebParam(name = "issued", partName = "issued")
        boolean issued);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeHistRecArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeHistRecArray getMoneyCodes(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeHistRecArrayV2
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeHistRecArrayV2 getMoneyCodesV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param policyNumber
     * @return
     *     returns com.cpsmart.wexclient.WSPolicy
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSPolicy getPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNumber", partName = "policyNumber")
        int policyNumber);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSPolicyDescriptionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSPolicyDescriptionArray getPolicyDescriptions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSSitePolicyDescriptionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSitePolicyDescriptionArray getSitePolicyDescriptions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSProductGroupArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSProductGroupArray getProductGroups(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSProductArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSProductArray getProducts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param locationIds
     * @return
     *     returns com.cpsmart.wexclient.WSTransLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransLocationArray getTransLocations(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "locationIds", partName = "locationIds")
        IntArray locationIds);

    /**
     * 
     * @param clientId
     * @param policyNum
     * @return
     *     returns com.cpsmart.wexclient.WSTransLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransLocationArray getTransLocationsForPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNum", partName = "policyNum")
        int policyNum);

    /**
     * 
     * @param cardNum
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSTransLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransLocationArray getTransLocationsForCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNum", partName = "cardNum")
        String cardNum);

    /**
     * 
     * @param cardNum
     * @param clientId
     * @param policyNum
     * @return
     *     returns com.cpsmart.wexclient.WSLocationGroupArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSLocationGroupArray getLocationGroups(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNum", partName = "cardNum")
        String cardNum,
        @WebParam(name = "policyNum", partName = "policyNum")
        int policyNum);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSLocationGroupDescriptionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSLocationGroupDescriptionArray getLocationGroupDescriptions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param name
     * @param ruleBased
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public int createLocGrp(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "ruleBased", partName = "ruleBased")
        boolean ruleBased);

    /**
     * 
     * @param clientId
     * @param groupId
     */
    @WebMethod
    public void removeLocGrp(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "groupId", partName = "groupId")
        int groupId);

    /**
     * 
     * @param clientId
     * @param groupId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String getLocGrpRule(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "groupId", partName = "groupId")
        int groupId);

    /**
     * 
     * @param clientId
     * @param groupId
     * @param rule
     */
    @WebMethod
    public void setLocGrpRule(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "groupId", partName = "groupId")
        int groupId,
        @WebParam(name = "rule", partName = "rule")
        String rule);

    /**
     * 
     * @param clientId
     * @param groupId
     * @return
     *     returns com.cpsmart.wexclient.IntArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public IntArray getLocGrpLocs(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "groupId", partName = "groupId")
        int groupId);

    /**
     * 
     * @param locs
     * @param clientId
     * @param groupId
     */
    @WebMethod
    public void setLocGrpLocs(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "groupId", partName = "groupId")
        int groupId,
        @WebParam(name = "locs", partName = "locs")
        IntArray locs);

    /**
     * 
     * @param locs
     * @param clientId
     * @param groupId
     */
    @WebMethod
    public void addLocGrpLocs(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "groupId", partName = "groupId")
        int groupId,
        @WebParam(name = "locs", partName = "locs")
        IntArray locs);

    /**
     * 
     * @param locs
     * @param clientId
     * @param groupId
     */
    @WebMethod
    public void removeLocGrpLocs(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "groupId", partName = "groupId")
        int groupId,
        @WebParam(name = "locs", partName = "locs")
        IntArray locs);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransactionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArray getTransactions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransactionExtArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionExtArray getTransactionsExt(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransExtLocArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransExtLocArray getTransExtLoc(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSMCTransExtLocArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMCTransExtLocArray getMCTransExtLoc(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSMCTransExtLocV2Array
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMCTransExtLocV2Array getMCTransExtLocV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSMCTransExtLocV3Array
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMCTransExtLocV3Array getMCTransExtLocV3(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param parentClientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransactionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArray getChildTransactions(
        @WebParam(name = "parentClientId", partName = "parentClientId")
        String parentClientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param parentClientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransactionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArray getChildTransactionsNew(
        @WebParam(name = "parentClientId", partName = "parentClientId")
        String parentClientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param parentClientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransactionArrayV2
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArrayV2 getChildTransactionsNewV2(
        @WebParam(name = "parentClientId", partName = "parentClientId")
        String parentClientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param parentClientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransactionArrayV3
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArrayV3 getChildTransactionsNewV3(
        @WebParam(name = "parentClientId", partName = "parentClientId")
        String parentClientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param parentClientId
     * @param begDate
     * @param endDate
     * @param childCarrierId
     * @return
     *     returns com.cpsmart.wexclient.WSTransactionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArray getOneCarrierChildTransaction(
        @WebParam(name = "parentClientId", partName = "parentClientId")
        String parentClientId,
        @WebParam(name = "childCarrierId", partName = "childCarrierId")
        int childCarrierId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param amount
     * @param clientId
     * @param issuedTo
     * @param notes
     * @param contractId
     * @param currency
     * @param masterContractId
     * @param feeType
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCode
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCode issueMoneyCode(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId,
        @WebParam(name = "masterContractId", partName = "masterContractId")
        int masterContractId,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "feeType", partName = "feeType")
        boolean feeType,
        @WebParam(name = "issuedTo", partName = "issuedTo")
        String issuedTo,
        @WebParam(name = "notes", partName = "notes")
        String notes,
        @WebParam(name = "currency", partName = "currency")
        String currency);

    /**
     * 
     * @param amount
     * @param clientId
     * @param refNumber
     * @param payroll
     * @param cardNumber
     */
    @WebMethod
    public void loadCash(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "refNumber", partName = "refNumber")
        String refNumber,
        @WebParam(name = "payroll", partName = "payroll")
        boolean payroll);

    /**
     * 
     * @param amount
     * @param clientId
     * @param refNumber
     * @param payroll
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSConfirmationDesc
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSConfirmationDesc loadCashV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "refNumber", partName = "refNumber")
        String refNumber,
        @WebParam(name = "payroll", partName = "payroll")
        boolean payroll);

    /**
     * 
     * @param checkStatus
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSChecksArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSChecksArray getRegisteredChecks(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate,
        @WebParam(name = "checkStatus", partName = "checkStatus")
        String checkStatus);

    /**
     * 
     * @param amount
     * @param clientId
     * @param driverId
     * @param refNumber
     * @param payroll
     */
    @WebMethod
    public void loadCashDriverId(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "refNumber", partName = "refNumber")
        String refNumber,
        @WebParam(name = "payroll", partName = "payroll")
        boolean payroll);

    /**
     * 
     * @param amount
     * @param clientId
     * @param driverId
     * @param refNumber
     * @param payroll
     * @return
     *     returns com.cpsmart.wexclient.WSConfirmationDesc
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSConfirmationDesc loadCashDriverIdV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "refNumber", partName = "refNumber")
        String refNumber,
        @WebParam(name = "payroll", partName = "payroll")
        boolean payroll);

    /**
     * 
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String login(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param clientId
     */
    @WebMethod
    public void logout(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param cardNumber
     */
    @WebMethod
    public void removeCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param clientId
     * @param card
     */
    @WebMethod
    public void setCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "card", partName = "card")
        WSCard card);

    /**
     * 
     * @param clientId
     * @param card
     */
    @WebMethod
    public void setCardv2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "card", partName = "card")
        WSCardv2 card);

    /**
     * 
     * @param clientId
     * @param smartPayDriver
     */
    @WebMethod
    public void setSmartPayDriver(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "SmartPayDriver", partName = "SmartPayDriver")
        WSSmartPayDriver smartPayDriver);

    /**
     * 
     * @param clientId
     * @param policy
     */
    @WebMethod
    public void setPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policy", partName = "policy")
        WSPolicy policy);

    /**
     * 
     * @param clientId
     * @param account
     */
    @WebMethod
    public void createSmartPayTransferAccount(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "account", partName = "account")
        WSSmartPayTransferDefinition account);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSSmartPayTransferAccountArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayTransferAccountArray getSmartPayTransferAccounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param accountId
     * @param clientId
     */
    @WebMethod
    public void deleteSmartPayTransferAccount(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "accountId", partName = "accountId")
        int accountId);

    /**
     * 
     * @param clientId
     * @param account
     */
    @WebMethod
    public void setSmartPayTransferAccount(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "account", partName = "account")
        WSSmartPayTransferAccount account);

    /**
     * 
     * @param fromCard
     * @param clientId
     * @param toCard
     */
    @WebMethod
    public void transferCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "fromCard", partName = "fromCard")
        String fromCard,
        @WebParam(name = "toCard", partName = "toCard")
        String toCard);

    /**
     * 
     * @param clientId
     * @param transferDefinition
     */
    @WebMethod
    public void createSmartPayScheduledTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "transferDefinition", partName = "transferDefinition")
        WSSmartPayScheduledTransferDefinition transferDefinition);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSSmartPayScheduledTransferArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayScheduledTransferArray getSmartPayScheduledTransfers(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param clientId
     * @param transferId
     */
    @WebMethod
    public void deleteSmartPayScheduledTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "transferId", partName = "transferId")
        int transferId);

    /**
     * 
     * @param clientId
     * @param moneyCode
     */
    @WebMethod
    public void voidMoneyCode(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "moneyCode", partName = "moneyCode")
        String moneyCode);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.StringArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public StringArray getPromptTypes(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSTransSummary
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransSummary transSummary(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @param begDate
     * @param endDate
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCodeSummary
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeSummary moneyCodeSummary(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param request
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSCardSummaryArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCardSummaryArray getCardSummaries(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "request", partName = "request")
        WSCardSummaryReq request);

    /**
     * 
     * @param request
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSCardSummaryArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCardSummaryArray getCardSummariesV2(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "request", partName = "request")
        WSCardSummaryV2Req request);

    /**
     * 
     * @param clientId
     * @param cardType
     * @return
     *     returns com.cpsmart.wexclient.StringArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public StringArray getCardsWithNoDriverId(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardType", partName = "cardType")
        String cardType);

    /**
     * 
     * @param clientId
     * @param contractId
     * @return
     *     returns com.cpsmart.wexclient.WSCreditLimits
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCreditLimits getCreditLimits(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId);

    /**
     * 
     * @param search
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSTranRejectArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTranRejectArray getTranRejects(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "search", partName = "search")
        WSTranRejectSearch search);

    /**
     * 
     * @param search
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSLastMileageArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSLastMileageArray getLastMileage(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "search", partName = "search")
        WSLastMileageSearch search);

    /**
     * 
     * @param unit
     * @param clientId
     * @param code
     * @param mileage
     */
    @WebMethod
    public void overrideLastMileage(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "unit", partName = "unit")
        String unit,
        @WebParam(name = "code", partName = "code")
        String code,
        @WebParam(name = "mileage", partName = "mileage")
        int mileage);

    /**
     * 
     * @param search
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSLocationArray searchLocation(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "search", partName = "search")
        WSLocationSearch search);

    /**
     * 
     * @param taxFlag
     * @param clientId
     * @param interstates
     * @param cardNumber
     * @param states
     * @return
     *     returns com.cpsmart.wexclient.WSGeoPriceLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSGeoPriceLocationArray getInterstatePriceLocations(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "interstates", partName = "interstates")
        String interstates,
        @WebParam(name = "states", partName = "states")
        String states,
        @WebParam(name = "taxFlag", partName = "taxFlag")
        boolean taxFlag);

    /**
     * 
     * @param taxFlag
     * @param clientId
     * @param latitude
     * @param searchRange
     * @param cardNumber
     * @param longitude
     * @return
     *     returns com.cpsmart.wexclient.WSGeoPriceLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSGeoPriceLocationArray getGeoPriceLocations(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "latitude", partName = "latitude")
        String latitude,
        @WebParam(name = "longitude", partName = "longitude")
        String longitude,
        @WebParam(name = "searchRange", partName = "searchRange")
        String searchRange,
        @WebParam(name = "taxFlag", partName = "taxFlag")
        boolean taxFlag);

    /**
     * 
     * @param code
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "valid", partName = "valid")
    public boolean verifyUser(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "code", partName = "code")
        String code);

    /**
     * 
     * @param clientId
     * @param transfer
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "transferId", partName = "transferId")
    public int doSmartPayAchTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "transfer", partName = "transfer")
        WSSmartPayAchTransfer transfer);

    /**
     * 
     * @param clientId
     * @param amounts
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "successful", partName = "successful")
    public boolean verifySmartPayTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "amounts", partName = "amounts")
        WSVerifySmartPayTransfer amounts);

    /**
     * 
     * @param clientId
     * @param count
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSSmartPayTransferHistoryArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayTransferHistoryArray smartPayTransferHistory(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "count", partName = "count")
        int count);

    /**
     * 
     * @param clientId
     * @param ppdDetailId
     */
    @WebMethod
    public void cancelPendingTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "ppdDetailId", partName = "ppdDetailId")
        long ppdDetailId);

    /**
     * 
     * @param clientId
     * @param application
     * @return
     *     returns com.cpsmart.wexclient.WSMobileSecurityArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMobileSecurityArray getMobileRoles(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "application", partName = "application")
        String application);

    /**
     * 
     * @param passwd
     * @param carrierId
     * @param userId
     * @return
     *     returns com.cpsmart.wexclient.StringArray
     */
    @WebMethod
    @WebResult(name = "ivrRoles", partName = "ivrRoles")
    public StringArray ivrLogin(
        @WebParam(name = "carrierId", partName = "carrierId")
        String carrierId,
        @WebParam(name = "passwd", partName = "passwd")
        String passwd,
        @WebParam(name = "userId", partName = "userId")
        String userId);

    /**
     * 
     * @param callinId
     * @param callinPin
     * @param carrierId
     * @return
     *     returns com.cpsmart.wexclient.WSIvrLoginWithPinResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public WSIvrLoginWithPinResponse ivrLoginWithPin(
        @WebParam(name = "carrierId", partName = "carrierId")
        String carrierId,
        @WebParam(name = "callinId", partName = "callinId")
        String callinId,
        @WebParam(name = "callinPin", partName = "callinPin")
        String callinPin);

    /**
     * 
     * @param callinId
     * @param currentPin
     * @param carrierId
     * @param newPin
     * @return
     *     returns com.cpsmart.wexclient.WSIvrLoginChangePinResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public WSIvrLoginChangePinResponse ivrLoginChangePin(
        @WebParam(name = "carrierId", partName = "carrierId")
        String carrierId,
        @WebParam(name = "callinId", partName = "callinId")
        String callinId,
        @WebParam(name = "currentPin", partName = "currentPin")
        String currentPin,
        @WebParam(name = "newPin", partName = "newPin")
        String newPin);

    /**
     * 
     * @param clientId
     * @param managedFuel
     */
    @WebMethod
    public void managedFuelAction(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "managedFuel", partName = "managedFuel")
        WSManagedFuel managedFuel);

    /**
     * 
     * @param clientId
     * @param managedFuelDriver
     */
    @WebMethod
    public void managedFuelDriverAction(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "managedFuelDriver", partName = "managedFuelDriver")
        WSManagedFuelDriver managedFuelDriver);

    /**
     * 
     * @param clientId
     * @param cardNumbers
     * @return
     *     returns com.cpsmart.wexclient.WSAllCashAvailArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSAllCashAvailArray getCurrentCashAllAmounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumbers", partName = "cardNumbers")
        StringArray cardNumbers);

    /**
     * 
     * @param clientId
     * @param authCode
     * @param registerCheckAuthorizaiton
     * @param status
     */
    @WebMethod
    public void registerCheck(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "registerCheckAuthorizaiton", partName = "registerCheckAuthorizaiton")
        WSRegisterCheckAuthorization registerCheckAuthorizaiton,
        @WebParam(name = "status", mode = WebParam.Mode.OUT, partName = "status")
        Holder<String> status,
        @WebParam(name = "authCode", mode = WebParam.Mode.OUT, partName = "authCode")
        Holder<String> authCode);

    /**
     * 
     * @param cardNum
     * @param clientId
     * @param latitude
     * @param unitNum
     * @param source
     * @param longitude
     */
    @WebMethod
    public void registerCardPosition(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNum", partName = "cardNum")
        String cardNum,
        @WebParam(name = "latitude", partName = "latitude")
        String latitude,
        @WebParam(name = "longitude", partName = "longitude")
        String longitude,
        @WebParam(name = "unitNum", partName = "unitNum")
        String unitNum,
        @WebParam(name = "source", partName = "source")
        String source);

    /**
     * 
     * @param clientId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "doesCardPosition", partName = "doesCardPosition")
    public boolean doesCardPosition(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param result
     * @param pin
     * @param driverId
     * @param carrierId
     * @param cardNumber
     */
    @WebMethod
    public void validCard(
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "pin", partName = "pin")
        String pin,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId,
        @WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result")
        Holder<String> result,
        @WebParam(name = "carrierId", mode = WebParam.Mode.OUT, partName = "carrierId")
        Holder<String> carrierId);

    /**
     * 
     * @param clientId
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "serverTime", partName = "serverTime")
    public XMLGregorianCalendar serverTime(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param result
     * @param driverId
     * @param carrierId
     * @param cardNumber
     */
    @WebMethod
    public void signupScale(
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId,
        @WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result")
        Holder<String> result,
        @WebParam(name = "carrierId", mode = WebParam.Mode.OUT, partName = "carrierId")
        Holder<String> carrierId);

    /**
     * 
     * @param clientId
     * @param contractId
     * @param ynFlag
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String setMcodeBillOnIssue(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId,
        @WebParam(name = "ynFlag", partName = "ynFlag")
        String ynFlag);

    /**
     * 
     * @param cardNum
     * @param clientId
     * @param newPin
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String setCardPin(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNum", partName = "cardNum")
        String cardNum,
        @WebParam(name = "newPin", partName = "newPin")
        String newPin);

    /**
     * 
     * @param clientId
     * @param policyNumber
     * @return
     *     returns com.cpsmart.wexclient.WSOrderTypesResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public WSOrderTypesResponse getOrderTypes(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNumber", partName = "policyNumber")
        int policyNumber);

    /**
     * 
     * @param orderType
     * @param clientId
     * @param policyNumber
     * @return
     *     returns com.cpsmart.wexclient.WSOrderStylesResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public WSOrderStylesResponse getOrderStyles(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNumber", partName = "policyNumber")
        int policyNumber,
        @WebParam(name = "orderType", partName = "orderType")
        int orderType);

    /**
     * 
     * @param orderType
     * @param requiredOnly
     * @param clientId
     * @param localeCode
     * @param policyNumber
     * @param cardStyle
     * @return
     *     returns com.cpsmart.wexclient.WSOrderChoicesResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public WSOrderChoicesResponse getOrderChoices(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNumber", partName = "policyNumber")
        int policyNumber,
        @WebParam(name = "orderType", partName = "orderType")
        int orderType,
        @WebParam(name = "cardStyle", partName = "cardStyle")
        int cardStyle,
        @WebParam(name = "localeCode", partName = "localeCode")
        String localeCode,
        @WebParam(name = "requiredOnly", partName = "requiredOnly")
        boolean requiredOnly);

    /**
     * 
     * @param clientId
     * @param orderId
     * @param requestStatus
     * @param order
     */
    @WebMethod
    public void createAndSubmitOrder(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "order", partName = "order")
        WSCreateAndSubmitOrderData order,
        @WebParam(name = "orderId", mode = WebParam.Mode.OUT, partName = "orderId")
        Holder<Long> orderId,
        @WebParam(name = "requestStatus", mode = WebParam.Mode.OUT, partName = "requestStatus")
        Holder<WSRequestStatus> requestStatus);

    /**
     * 
     * @param clientId
     * @param orderId
     * @param newOrderData
     * @param requestStatus
     */
    @WebMethod
    public void createOrder(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "newOrderData", partName = "newOrderData")
        WSNewOrderData newOrderData,
        @WebParam(name = "orderId", mode = WebParam.Mode.OUT, partName = "orderId")
        Holder<Long> orderId,
        @WebParam(name = "requestStatus", mode = WebParam.Mode.OUT, partName = "requestStatus")
        Holder<WSRequestStatus> requestStatus);

    /**
     * 
     * @param clientId
     * @param orderId
     * @param updOrderData
     * @return
     *     returns com.cpsmart.wexclient.WSRequestStatus
     */
    @WebMethod
    @WebResult(name = "requestStatus", partName = "requestStatus")
    public WSRequestStatus updateOrder(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId,
        @WebParam(name = "updOrderData", partName = "updOrderData")
        WSUpdOrderData updOrderData);

    /**
     * 
     * @param clientId
     * @param orderId
     * @param updOrderCardsData
     * @return
     *     returns com.cpsmart.wexclient.WSRequestStatus
     */
    @WebMethod
    @WebResult(name = "requestStatus", partName = "requestStatus")
    public WSRequestStatus updateOrderCards(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId,
        @WebParam(name = "updOrderCardsData", partName = "updOrderCardsData")
        WSUpdOrderCardsData updOrderCardsData);

    /**
     * 
     * @param clientId
     * @param orderId
     * @return
     *     returns com.cpsmart.wexclient.WSGetOrderData
     */
    @WebMethod
    @WebResult(name = "orderData", partName = "orderData")
    public WSGetOrderData getOrder(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId);

    /**
     * 
     * @param clientId
     * @param cardSelections
     * @param orderId
     * @return
     *     returns com.cpsmart.wexclient.WSGetOrderCardsData
     */
    @WebMethod
    @WebResult(name = "orderCardsData", partName = "orderCardsData")
    public WSGetOrderCardsData getOrderCards(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId,
        @WebParam(name = "cardSelections", partName = "cardSelections")
        String cardSelections);

    /**
     * 
     * @param clientId
     * @param orderId
     * @return
     *     returns com.cpsmart.wexclient.WSRequestStatus
     */
    @WebMethod
    @WebResult(name = "requestStatus", partName = "requestStatus")
    public WSRequestStatus submitOrder(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId);

    /**
     * 
     * @param clientId
     * @param orderId
     * @return
     *     returns com.cpsmart.wexclient.WSRequestStatus
     */
    @WebMethod
    @WebResult(name = "requestStatus", partName = "requestStatus")
    public WSRequestStatus stopOrder(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId);

    /**
     * 
     * @param clientId
     * @param orderId
     * @return
     *     returns com.cpsmart.wexclient.WSRequestStatus
     */
    @WebMethod
    @WebResult(name = "requestStatus", partName = "requestStatus")
    public WSRequestStatus deleteOrder(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId);

    /**
     * 
     * @param filter
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSFindOrderSummaryData
     */
    @WebMethod
    @WebResult(name = "results", partName = "results")
    public WSFindOrderSummaryData findOrders(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "filter", partName = "filter")
        WSFindOrderSummaryFilter filter);

    /**
     * 
     * @param clientId
     * @param policy
     * @return
     *     returns com.cpsmart.wexclient.WSPolicyRefreshingLimitsData
     */
    @WebMethod
    @WebResult(name = "policyRefreshingLimitsData", partName = "policyRefreshingLimitsData")
    public WSPolicyRefreshingLimitsData getPolicyRefreshingLimits(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policy", partName = "policy")
        int policy);

    /**
     * 
     * @param clientId
     * @param policyRefreshingLimitsData
     * @param policy
     * @return
     *     returns com.cpsmart.wexclient.WSRequestStatus
     */
    @WebMethod
    @WebResult(name = "requestStatus", partName = "requestStatus")
    public WSRequestStatus setPolicyRefreshingLimits(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policy", partName = "policy")
        int policy,
        @WebParam(name = "policyRefreshingLimitsData", partName = "policyRefreshingLimitsData")
        WSPolicyRefreshingLimitsData policyRefreshingLimitsData);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSCardRefreshingLimitsData
     */
    @WebMethod
    @WebResult(name = "cardRefreshingLimitsData", partName = "cardRefreshingLimitsData")
    public WSCardRefreshingLimitsData getCardRefreshingLimits(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param cardRefreshingLimitsData
     * @param clientId
     * @param cardNumber
     * @return
     *     returns com.cpsmart.wexclient.WSRequestStatus
     */
    @WebMethod
    @WebResult(name = "requestStatus", partName = "requestStatus")
    public WSRequestStatus setCardRefreshingLimits(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "cardRefreshingLimitsData", partName = "cardRefreshingLimitsData")
        WSCardRefreshingLimitsData cardRefreshingLimitsData);

    /**
     * 
     * @param carrierDiscount
     * @param clientId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String setCarrierDiscount(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "carrierDiscount", partName = "carrierDiscount")
        WSCarrierGetsDiscountArray carrierDiscount);

    /**
     * 
     * @param lookup
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSCarrierGetsDiscountDataArray
     */
    @WebMethod
    @WebResult(name = "carrierDiscountData", partName = "carrierDiscountData")
    public WSCarrierGetsDiscountDataArray pullCarrierGetsDiscountData(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "lookup", partName = "lookup")
        String lookup);

    /**
     * 
     * @param clientId
     * @param endDate
     * @param startDate
     * @return
     *     returns com.cpsmart.wexclient.WSChildTranRejectArray
     */
    @WebMethod
    @WebResult(name = "childTranRejects", partName = "childTranRejects")
    public WSChildTranRejectArray getChildTranRejects(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "startDate", partName = "startDate")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cpsmart.wexclient.WSAllowedOrderTypesResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public WSAllowedOrderTypesResponse getAllowedOrderTypes(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param data
     * @param orderId
     * @param requestStatus
     */
    @WebMethod
    public void issueNewPayrollCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "data", partName = "data")
        WSIssueNewPayrollCardData data,
        @WebParam(name = "orderId", mode = WebParam.Mode.OUT, partName = "orderId")
        Holder<Long> orderId,
        @WebParam(name = "requestStatus", mode = WebParam.Mode.OUT, partName = "requestStatus")
        Holder<WSRequestStatus> requestStatus);

    /**
     * 
     * @param clientId
     * @param data
     * @param orderId
     * @param requestStatus
     */
    @WebMethod
    public void issueNewPersonalizedPayrollCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "data", partName = "data")
        WSIssueNewPersonalizedPayrollCardData data,
        @WebParam(name = "orderId", mode = WebParam.Mode.OUT, partName = "orderId")
        Holder<Long> orderId,
        @WebParam(name = "requestStatus", mode = WebParam.Mode.OUT, partName = "requestStatus")
        Holder<WSRequestStatus> requestStatus);

    /**
     * 
     * @param clientId
     * @param data
     * @param orderId
     * @param requestStatus
     */
    @WebMethod
    public void reissueDamagedCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "data", partName = "data")
        WSReissueDamagedCardData data,
        @WebParam(name = "orderId", mode = WebParam.Mode.OUT, partName = "orderId")
        Holder<Long> orderId,
        @WebParam(name = "requestStatus", mode = WebParam.Mode.OUT, partName = "requestStatus")
        Holder<WSRequestStatus> requestStatus);

    /**
     * 
     * @param clientId
     * @param data
     * @param orderId
     * @param requestStatus
     */
    @WebMethod
    public void replaceLostOrStolenCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "data", partName = "data")
        WSReplaceLostOrStolenCardData data,
        @WebParam(name = "orderId", mode = WebParam.Mode.OUT, partName = "orderId")
        Holder<Long> orderId,
        @WebParam(name = "requestStatus", mode = WebParam.Mode.OUT, partName = "requestStatus")
        Holder<WSRequestStatus> requestStatus);

    /**
     * 
     * @param clientId
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "cardNumber", partName = "cardNumber")
    public String createInfoLimitCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "data", partName = "data")
        WSCreateInfoLimitCardData data);

    /**
     * 
     * @param clientId
     * @param data
     */
    @WebMethod
    public void deleteInfoLimitCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "data", partName = "data")
        WSDeleteInfoLimitCardData data);

    /**
     * 
     * @param amount
     * @param clientId
     * @param issuedTo
     * @param notes
     * @param contractId
     * @param currency
     * @param masterContractId
     * @param feeType
     * @param prompts
     * @return
     *     returns com.cpsmart.wexclient.WSMoneyCode
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCode issueMoneyCodePrompts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId,
        @WebParam(name = "masterContractId", partName = "masterContractId")
        int masterContractId,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "feeType", partName = "feeType")
        boolean feeType,
        @WebParam(name = "issuedTo", partName = "issuedTo")
        String issuedTo,
        @WebParam(name = "notes", partName = "notes")
        String notes,
        @WebParam(name = "currency", partName = "currency")
        String currency,
        @WebParam(name = "prompts", partName = "prompts")
        WSMonCodesInfoArray prompts);

}
